---
abstract: 'Template::Tiny backend to Dancer'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Template-Tiny
provides:
  Dancer::Template::Tiny:
    file: lib/Dancer/Template/Tiny.pm
    version: 0.02
requires:
  Dancer: 1.15
  Template::Tiny: 0.11
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
